/* Main.c
   STM32CubeIDE project skeleton for Edge Keyword Spotter (STM32)
   - Uses HAL + FreeRTOS
   - audio_capture: I2S + DMA continuous capture (half/full callbacks)
   - inference: stub which can be replaced with TFLM integration
   Instructions: create CubeMX project for your MCU, enable I2S (or SAI), DMA, FreeRTOS.
*/

#include "main.h"
#include "cmsis_os.h"
#include "audio_capture.h"
#include "inference.h"
#include "gpio.h"
#include "usart.h"

static osThreadId_t audioProducerHandle;
static osThreadId_t inferenceConsumerHandle;
static QueueHandle_t audioQueue;

void SystemClock_Config(void); // generated by CubeMX
void MX_GPIO_Init(void);
void MX_I2Sx_Init(void);
void MX_DMA_Init(void);
void MX_USART2_UART_Init(void);

void audioProducerTask(void *argument)
{
    size_t frame_bytes = AUDIO_CAPTURE_FRAME_BYTES;
    uint8_t *frame = pvPortMalloc(frame_bytes);
    if (!frame) {
        Error_Handler();
    }

    for (;;) {
        if (audio_capture_get_frame(frame, frame_bytes, pdMS_TO_TICKS(2000)) == HAL_OK) {
            if (xQueueSend(audioQueue, &frame, pdMS_TO_TICKS(100)) != pdPASS) {
                // queue full, drop
            } else {
                frame = pvPortMalloc(frame_bytes);
                if (!frame) {
                    Error_Handler();
                }
            }
        }
    }
}

void inferenceConsumerTask(void *argument)
{
    uint8_t *recv_frame;
    for (;;) {
        if (xQueueReceive(audioQueue, &recv_frame, portMAX_DELAY) == pdPASS) {
            // run inference on int16 samples
            bool detected = inference_run_on_audio((const int16_t *)recv_frame, AUDIO_CAPTURE_FRAME_SAMPLES);
            if (detected) {
                // toggle LED or send message via UART
                HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);
                HAL_Delay(150);
                HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);
            }
            vPortFree(recv_frame);
        }
    }
}

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_I2Sx_Init();
    MX_USART2_UART_Init();

    // init audio capture HAL wrapper
    audio_capture_config_t cfg = {
        .sample_rate = AUDIO_CAPTURE_SAMPLE_RATE,
        .bits_per_sample = AUDIO_CAPTURE_BITS_PER_SAMPLE,
        .channels = AUDIO_CAPTURE_CHANNELS,
    };
    if (audio_capture_init(&cfg) != HAL_OK) {
        Error_Handler();
    }

    audioQueue = xQueueCreate(4, sizeof(uint8_t *));
    if (!audioQueue) Error_Handler();

    xTaskCreate(audioProducerTask, "audioProd", 4*1024, NULL, 6, &audioProducerHandle);
    xTaskCreate(inferenceConsumerTask, "infCons", 6*1024, NULL, 5, &inferenceConsumerHandle);

    // start scheduler
    vTaskStartScheduler();

    for (;;);
}
